### ISSUE TITLE
RV Tutorial Issues Post Here

### ISSUE THREAD

**Issue by hayate0304** [hayate0304/Rsymbulate#9]
If you want to do `X(outcome)`, please do `call(X, outcome)` instead

**Comment by kevindavisross** [comment]
I've attached a pdf file with some tests.  I've reviewed functionality but not the actual code.  Here are a few issues/comments.

- I'm not a fan of the `call(X, outcome)` syntax to call a RV as a function to return a value for a particular outcome.  But if just `X(outcome)` isn't possible, maybe `Evaluate` would be better; are we stuck with "call"?
- Is it possible to  transform RVs without `Apply`?  Like `5-X` or `2*X`?  Is it possible to transform with common functions without `Apply`, like `exp(X)` or `log(X)`?  Even if we can't call a general function on a RV without `Apply`, it would still be nice to apply linear transformations.
- Add the code to install the necessary R packages, like ggplot2.
- What about vectorized operations in simulation space?  Like `x = (X %>% sim(10000))` then `x - mean(x)`?
- Need to implement operations on RV: adding, multiplying, etc.  Is `%+%` for adding RVs?  If so, it doesn't appear to be working.

[TEST-RV.pdf](https://github.com/hayate0304/Rsymbulate/files/2322393/TEST-RV.pdf)

**Comment by hayate0304** [comment]
- I'll create a math.R for the `exp(X), log(X)`, transformations.
- I'll check your issues and let you you know in this post if they're done.

**Comment by hayate0304** [comment]
Can you give a specific example about vectorized operations in simulation space? I tried this in Python and they return errors.
![image](https://user-images.githubusercontent.com/23329938/44806074-c7212c80-ab7a-11e8-914e-d1e5b9f51a1e.png)

**Comment by dlsun** [comment]
There shouldn't be a need to create a `math.R` file. You should be able to get `exp(X)` to work just by defining the function `RV.exp` in the `RV` class.

**Comment by kevindavisross** [comment]
That's weird about the `x-mean(x)` example.  It works with `x - x.mean()`.  Not sure if the discrepancy is intentional.  
![sym-mean-example](https://user-images.githubusercontent.com/27861382/44806774-b2459880-ab7c-11e8-9c68-7d7b4a7d1812.PNG)

**Comment by hayate0304** [comment]
- Functions are lower case now. I found out a way for that.
- I added 4 vectorized ops: `+, -, *, /` to work like the above case
- I added transformations for: `sqrt, exp, sin, cos, tan, factorial and log`. You can do` y = sqrt(x) `like in Python
- You can test `-, +, *, /` between 2 RVs, or between a RV and scalar
- R does not support custom unary operator so right now we can't do something like `-log(U)`. 
- I'll start on conditions tomorrow

**Comment by kevindavisross** [comment]
I haven't gotten too far with my review, but I have found a few examples that aren't working properly - they don't return errors, but the results aren't correct.  Both these examples involve adding constants to RV, but I don't know if that is the full extent of the problem.  Please check into these and related examples.

Please also add Poisson and Exponential distributions, since these provide a few more examples to test.

![image](https://user-images.githubusercontent.com/27861382/44923658-c95fc400-acfd-11e8-830c-6ca894407673.png)

![image](https://user-images.githubusercontent.com/27861382/44923709-ed230a00-acfd-11e8-92ce-83589fac754b.png)

**Comment by hayate0304** [comment]
- Ok, I fixed that and added those 2 distributions
- I also changed the print method of Results object, it now prints the $results automatically instead of the whole object. Dr. Sun thinks this is fine but it may make users confused and think that the object is vector. Let me know what you think

**Comment by kevindavisross** [comment]
- I think the way you have the print method of Results now is cleaner than before.
- Check how you are setting bin endpoints for histogram.  For example, for Exponential, the first bin starts below 0, so it makes the plot look weird.
![image](https://user-images.githubusercontent.com/27861382/45040044-ea842580-b019-11e8-9421-5a0f30e3e6ee.png)
- Add `cov` and `corr`
- Lower priority for now: `mean` (and `var`, etc) for random vector should return mean for each component

**Comment by hayate0304** [comment]
- **Behold my masterpiece** : I got the slicing to work but you need to do `x[[1]]` instead of `x[1]` since its a list. I couldn't do unpacking although I got an idea for it. However, in my idea, the syntax and amount of time for user to do unpacking is tired and would be equal the time when they do this:
`x = RV(p)`
`y = x[[1]]`
- I do not set any bin endpoints for the histogram. I tried many different arguments but could not get the desired result yet. Feel like could not do anything about it.
- I added `cov` and `cor` (Dr. Sun wants `cor` since it matches with R)
- I got the basic things for Conditioning done, however, I need to test it (haven't tested yet).
- One problem about the operator `%>% `which is to test for conditions greater than, it wouldn't work since I implemented magrittr package inside symbulate. So right now not sure how you want to fix that.

**Comment by kevindavisross** [comment]
Can you post some examples of how the slicing syntax is supposed to work?  I keep getting error: object 'ps' not found. Am I missing a package?

**Comment by hayate0304** [comment]
No you don't, I just quick fix that. You can install again.

**Comment by kevindavisross** [comment]
I'm running into some errors.

Many are of the "Events must be defined on the same probability space" type, like the following.
```
P = Poisson(1) %*% Poisson(2)
XY = RV(P)
X = XY[[1]]
Y = XY[[2]]
(X %+% Y) %>% sim(10000) %>% tabulate(normalize=TRUE)
```

If `X = RV(P)` then `X[[i]]` should be automatically defined on `P`, the same probability space as `X`.

The next example does not produce an error, but the results are incorrect.  X and Y should have a BivariateNormal distribution with correlation 0.6.
```{r}
P = Normal(0, 1) %^% 2
Z = RV(P)
X = Z[[1]]
Y = (0.6 %*% X) %+% (sqrt(1-0.6^2) %*% Z[[2]])
(X %&% Y) %>% sim(10000) %>% plot
```

Regarding `cov` and `cor`: you might have discussed this with @dlsun already, but should these return a number or a matrix when just two RVs?  It's currently a matrix, but to be consistent with Python version it should be a number.

**Comment by hayate0304** [comment]
I fixed the first problem and the `cov, cor` for 2 RVs but haven't pushed yet. I thought what I had yesterday was ok but now it has another problem with the `%&%` that I need to work on since R has this so much different than Python.

**Comment by hayate0304** [comment]
- Okay, you can test all those again.
- I also added "mean (and var, etc) for random vector should return mean for each component". Not sure exactly what this means, let me know if it's wrong when you test it.
- You can test things related to the first 5 sections in module "**conditioning**". 
- Please use `%>>%` for `> `and `%<<%` for `< `because `%>%` conflicts with the pipe thing
- Use `%~%` for **not** though I haven't tested much with this operator.
- use `rep(c("clubs", "diamonds", "hearts", "spades"), 13)` for something like `['clubs', 'diamonds', 'hearts', 'spades'] * 13`

**Comment by kevindavisross** [comment]
- Slicing seems to be working well.
- Conditioning seems to be working well. But I'd like to continue with some more tests.
- Can you give an example of how `%~%` is supposed to work?
- `mean` for vectors seems to be working correctly.  I meant that `(X %&% Y) %>% sim(1000) %>% mean` should return a vector (mean of x values, mean of y values).  This is what it's doing.
- Please look into the histogram bin issue again.  Here's one suggestion using `breaks`, but please play around with different strategies and examples to see what works best
```
x = rexp(10000)
ggplot(data=data.frame(x), aes(x)) + geom_histogram(breaks=seq(min(x), max(x), (max(x)-min(x))/100))
```
- This is not a priority, but is maybe not too hard to implement given that you've been working with events and conditioning: Add the ability to [simulate events](https://dlsun.github.io/symbulate/rv.html#RVevent)
- I have a few examples like the following which at first ran fine, then I did the ggplot example above in the console, and then they didn't work.  I imagine it's something about `%+%` because `X` and `Y` both ran fine on their own.  If I restart my R session again everything is fine.  Is this behavior expected?
```
P = Uniform(0, 1) %^% 2
Z = RV(P)
X = -1 %*% log(Z[[1]])
Y = -1 %*% log(Z[[2]])
(X %+% Y) %>% sim(10000) %>% plot
# returns: "Error in sim.default(., 10000) : Could not perform the function on this object"
```

**Comment by hayate0304** [comment]
- Can you show me how `~` work in Python, there's no guide about how it works on the module
- I'm investigating the ggplot issue. Quite Interesting. Will work on the histogram bin issue.

**Comment by kevindavisross** [comment]
Here's a complement example; basically `~A` is complement of A 
```
P = BoxModel([1, 2, 3, 4], size=2)
X = RV(P, sum)
Y = RV(P, max)
(X | (~(Y == 4)) ).sim(10000).tabulate()
```

**Comment by hayate0304** [comment]
- Muahahaha, I so admire myself. I got the infix operators work for both side. You can test them all again without %%. And it won't mess up with ggplot anymore.
- I fix the histogram with your code and a little bit change. Thanks for that.
- `~` is not a unary operator in R so I changed to `!` instead.
- I added simulate events.
- Some unresolved issues I'm working on is adding `density, tile, violin and hist for plot()` 2 dimensions. I won't work on "marginal" now since I think it's quite complicated

**Comment by kevindavisross** [comment]
- It's SO much better without `%%` around everything.  Thanks for making that work.
- I have no idea what is happening, but sometimes the code outputs `"Here"` or `"Inside"`.  There doesn't seem to be any recognizable pattern to when it happens or not.
- That's great that you're working on some more graphics, but I think there are other priorities.  In particular, sure-ing up the existing code and adding more common distributions to probability space (Gamma, NegativeBinomial, etc; see the list of what's available in the Python version documentation.)
- In terms of plots, do you think you can implement plotting a true pdf/pmf (`Poisson(1) %>% plot` or `Normal(0, 1) %>% plot`) and the ability to overlay a true pmf/pdf on a simulated impulse plot/histogram?  See the examples on the common discrete and continuous distributions pages of the documentation.  I would prefer that functionality over some of the other plots you suggested.

**Comment by hayate0304** [comment]
- Those were my debugging code, I removed it.
- I'm working on plotting pdf/pmf.

**Comment by hayate0304** [comment]
- I added plotting for true pdf/pmf.
- Right now, I have only 1 solution for the overlaying. You need to do something like this:
`sims = RV(Hypergeometric(n=5, N0=5, N1=10)) %>% sim(10000)`
`a = sims %>% plot()`
`Hypergeometric(5, 5, 10) %>% plot(new = a)`
- Basically, I added an argument for the plot method of Distribution. And then we need to pass the ggplot object so that we can use that object to `+` more components. R is quite hard to do overlay if we don't know beforehand. For now, that's what I have.
- Bernoulli, Hypergeometric are added. Will add more tomorrow.

**Comment by kevindavisross** [comment]
- Normal is plotting like a discrete distribution instead of smooth continuous curve
- Some plots are displaying twice, like the one produced here
```
P = Uniform(0, 1) ^ 2
X = RV(P, min)
Y = RV(P, max)
(X | (abs(Y - 0.7) < 0.01) ) %>% sim(1000) %>% plot
```
- Some plots aren't working anymore.  In the above example, replacing X with `X & Y` in the plot line returns 
`Error in plot.RVResults(.) : object 'g' not found`
- The overlay didn't work in the following example.  The overlay - and other plot functionality - can wait till later.  Priority now is to make sure impulse, histogram, and scatter work; some of the changes you made broke some of the existing functionality.
```
p = RV(Poisson(2.2)) %>% sim(10000) %>% plot
Poisson(2.2) %>% plot(new=p)
```

**Comment by hayate0304** [comment]
- I fixed them.
- I fixed the basic overlay problem. Haven't tested with the complicated examples yet.
- I added the rest of the common distributions. You can test those, especially the LogNormal, since R `lnorm ` behaves different from `numpy `. I figured out a way but not sure if it's completely correct.

**Comment by kevindavisross** [comment]
Are all your most recent changes on GitHub?  I am still getting the same errors as before.

**Comment by hayate0304** [comment]
I think maybe because your install got error. You can try install again.
